### ISSUE TITLE
Miscategorizing some encounters

### ISSUE THREAD

**Issue by zarmstrong** [Mcgode/pf2-encounter-planner#1]
Using an encounter out of The Slithering on pg 13, it shows a level 6 and level 4 creature vs a part of four level 5 players is a moderate encounter. The planner shows it as severe at 90xp per player. It seems paizo expects there to be a bigger buffer between moderate and severe.  Perhaps starting severe at 100 might be more appropriate.

**Comment by zarmstrong** [comment]
Another example is on page 29 -- level 6 part, 1 x lvl 7 and 2 x lvl 3 monster = moderate in book, severe in encounter planner

**Comment by Mcgode** [comment]
Merged #2. Thanks for the contribution

Sorry about the delay, repo notifications were off for some reason.
